# importing function to create a random situation
import random

# prompts the user if he want to play a game yes or no
play = input("You would you like to play a number guessing game? ")

life = 3
# assigns a random number generated by the program to num
num = random.randint(1, 11)

if play.lower() == "yes":
    # creates a loop so the program runs until it is stopped
    while life != 0:
        try:
            # prompts the user to guess/enter a number
            guess = input("Please guess the number I am thinking of: ")

            # converts the string to an integer and determines if it's the number chosen by the program
            if int(guess) == num:
                print("Wow! You are right,", num, "was the number I was thinking about.")

                # ask the user for an input to continue or end the game
                cont = input("Would you like to continue or end? ")

                # if the user enters "continue" the game will continue.
                if cont.lower() == "continue":
                    continue

                # if the user enters "end" the game will end.
                elif cont.lower() == "end":
                    break  # breaks the loop
                else:
                    print("Please decide to continue or end the game.\n Thank you.")
                    continue
            elif int(guess) > num:
                print("Wrong guess, your number is too high.")
                life -= 1
            elif int(guess) < num:
                print("Wrong guess, your number is too low.")
                life -= 1
            if life == 0:
                print("GAME OVER!!! You have exhausted all your lives. Have a nice death ")
            else:
                print("I was not thinking of ", guess, ". Try again. You have", life, "lives left.")

        except ValueError:
            print("Please enter an integer :).")

else:
    print("Oh okay I understand. Goodbye :(")
